# events/urls.py

from rest_framework.routers import DefaultRouter
from django.urls import path, include
from . import views

# Router for Event listing (read-only)
router = DefaultRouter()
router.register(r'events', views.EventViewSet)

urlpatterns = [
    # Includes all routes generated by the router (e.g., /events/, /events/1/)
    path('', include(router.urls)),
    
    # Custom path for the automated POST-only Event Registration ViewSet
    # Accessible at: /api/v1/events/register/
    path('register/', views.RegisterForEventViewSet.as_view({'post': 'create'}), name='event-register'),
]