# Generated by Django 5.2.7 on 2025-11-03 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(help_text='13-digit ISBN.', max_length=13, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.IntegerField(default=0, help_text='Current number of units in stock.')),
                ('cover_image', models.ImageField(blank=True, help_text='Book cover image.', null=True, upload_to='book_covers/')),
                ('is_active', models.BooleanField(default=True, help_text='Designates if the book is available for purchase.')),
                ('genres', models.ManyToManyField(related_name='books', to='shop.genre')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, help_text='The final total price of the order.', max_digits=10)),
                ('user', models.ForeignKey(help_text='The user who placed the order (null if guest or user deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title_snapshot', models.CharField(editable=False, max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, help_text='The price of the book at the exact time of purchase.', max_digits=6)),
                ('book', models.ForeignKey(help_text='The book purchased. Set to null if the book is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'unique_together': {('order', 'book')},
            },
        ),
    ]
