# Generated by Django 5.2.7 on 2025-12-03 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sold_count',
            field=models.IntegerField(default=0, help_text='Cached total units sold for this book.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='books', to='shop.genre'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book',
            field=models.ForeignKey(help_text='The book purchased. Set to null if the book is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.book'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=0, help_text='The price of the book at the exact time of purchase.', max_digits=9),
        ),
    ]
