# Generated by Django 5.2.7 on 2025-12-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_book_sold_count_alter_book_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('books', models.ManyToManyField(blank=True, related_name='recommended_groups', to='shop.book')),
            ],
            options={
                'verbose_name': 'Recommended Book Group',
                'verbose_name_plural': 'Recommended Book Groups',
            },
        ),
    ]
