# Generated by Django 5.2.7 on 2025-11-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, help_text="The user's primary delivery address.", null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text="The user's contact phone number for delivery.", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, help_text="The user's postal code for shipping.", max_length=20, null=True),
        ),
    ]
